"""update table tbl_users

Revision ID: 0a66c5811547
Revises: cc90b55e45cf
Create Date: 2025-08-09 19:14:55.665790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a66c5811547'
down_revision: Union[str, None] = 'cc90b55e45cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_users', 'phone',
               existing_type=sa.VARCHAR(length=13),
               nullable=True,
               existing_server_default=sa.text("'1234567891011'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_users', 'phone',
               existing_type=sa.VARCHAR(length=13),
               nullable=False,
               existing_server_default=sa.text("'1234567891011'::character varying"))
    # ### end Alembic commands ###
