"""create user table

Revision ID: 243d89800307
Revises: 
Create Date: 2025-06-17 09:25:29.053656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '243d89800307'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_users_email'), table_name='tbl_users')
    op.drop_index(op.f('ix_tbl_users_username'), table_name='tbl_users')
    op.drop_table('tbl_users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('email', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('USER', 'ADMIN', 'LIBRARIAN', name='roles'), autoincrement=False, nullable=False),
    sa.Column('is_confirmed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('mfa_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('totp_secret', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('tbl_users_pkey'))
    )
    op.create_index(op.f('ix_tbl_users_username'), 'tbl_users', ['username'], unique=True)
    op.create_index(op.f('ix_tbl_users_email'), 'tbl_users', ['email'], unique=True)
    # ### end Alembic commands ###
