"""update tables

Revision ID: cc90b55e45cf
Revises: 133a8eb14c74
Create Date: 2025-07-29 09:25:50.039371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc90b55e45cf'
down_revision: Union[str, None] = '133a8eb14c74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_reservations', sa.Column('status', sa.Enum('WAITING', 'READY', 'EXPIRED', 'FULFILLED', 'CANCELLED', name='reservationstatus'), nullable=False))
    op.drop_column('tbl_reservations', 'state')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_reservations', sa.Column('state', postgresql.ENUM('ACTIVE', 'COMPLETED', 'CANCELED', name='reservationstatus'), autoincrement=False, nullable=False))
    op.drop_column('tbl_reservations', 'status')
    # ### end Alembic commands ###
